spring.application.name=securityAr

spring.security.user.name=admin
spring.security.user.password=admin

spring.datasource.url=jdbc:h2:mem:testdbea
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.app.jwtSecret =nddsbfsjufjufwwiugs
spring.app.jwtExpirationMs = 3000000000000000000000000000